name: "Continuous Integration"

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
  COMPOSER_UPDATE_FLAGS: ""

jobs:
  phpunit-mariadb:
    name: Test PHP ${{ matrix.php }}, ${{ matrix.database }}, ${{ matrix.dependencies }} deps
    runs-on: ubuntu-latest
    # don't mark the whole pipeline failed if one of those fails, there might
    # be incompatibilities with upcoming PHP versions
    continue-on-error: ${{ matrix.php == '8.6' }}
    services:
      mariadb:
        image: mariadb:12@sha256:628f228f0fd5913a220438693576b29b6fe4dc1fa0a1298c0e98579fae28635f
        env:
          MARIADB_USER: dbtest
          MARIADB_PASSWORD: dbtest
          MARIADB_DATABASE: dbtest
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
          MARIADB_MYSQL_LOCALHOST_USER: 1
          MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
        options: >-
          --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
    strategy:
      matrix:
        php: [ '8.5', '8.6' ]
        database: [ mariadb ]
        dependencies: [ lowest, highest ]
      fail-fast: false # continue the other jobs if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Common PHP setup
        uses: ./.github/actions/php-setup
        with:
          php: ${{ matrix.php }}
          dependencies: ${{ matrix.dependencies }}

      - name: Run tests on MariaDB
        env:
          DATABASE_URL: mysql://dbtest:dbtest@127.0.0.1:3306/dbtest?serverVersion=mariadb-12.0.0&charset=utf8mb4
        run: vendor/bin/phpunit --log-junit build/logs/phpunit/junit.xml

      - name: Upload test results
        uses: ./.github/actions/upload-phpunit-logs
        with:
          php: ${{ matrix.php }}
          database: ${{ matrix.database }}
          dependencies: ${{ matrix.dependencies }}

  phpunit-mysql:
    name: Test PHP ${{ matrix.php }}, ${{ matrix.database }}, ${{ matrix.dependencies }} deps
    runs-on: ubuntu-latest
    # don't mark the whole pipeline failed if one of those fails, there might
    # be incompatibilities with upcoming PHP versions
    continue-on-error: ${{ matrix.php == '8.6' }}
    services:
      mysql:
        image: mysql:9@sha256:8fdf311514c91fa5014e93e98e19d7f5d9eb162a462c13100c956dacc278ee21
        env:
          MYSQL_USER: dbtest
          MYSQL_PASSWORD: dbtest
          MYSQL_DATABASE: dbtest
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
    strategy:
      matrix:
        php: [ '8.5', '8.6' ]
        database: [ mysql ]
        dependencies: [ lowest, highest ]
      fail-fast: false # continue the other jobs if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Common PHP setup
        uses: ./.github/actions/php-setup
        with:
          php: ${{ matrix.php }}
          dependencies: ${{ matrix.dependencies }}

      - name: Run tests on MySQL
        env:
          DATABASE_URL: mysql://dbtest:dbtest@127.0.0.1:3306/dbtest?serverVersion=9.0&charset=utf8mb4
        run: vendor/bin/phpunit --log-junit build/logs/phpunit/junit.xml

      - name: Upload test results
        uses: ./.github/actions/upload-phpunit-logs
        with:
          php: ${{ matrix.php }}
          database: ${{ matrix.database }}
          dependencies: ${{ matrix.dependencies }}

  phpunit-postgres:
    name: Test PHP ${{ matrix.php }}, ${{ matrix.database }}, ${{ matrix.dependencies }} deps
    runs-on: ubuntu-latest
    # don't mark the whole pipeline failed if one of those fails, there might
    # be incompatibilities with upcoming PHP versions
    continue-on-error: ${{ matrix.php == '8.6' }}
    services:
      postgres:
        image: postgres:18@sha256:c2d42a104eb6b37b286a2d9c5cf83f349de4d6516d513d00a2bd9610e2c2e5e4
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: dbtest
          POSTGRES_PASSWORD: dbtest
          POSTGRES_DB: dbtest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        php: [ '8.5', '8.6' ]
        database: [ postgres ]
        dependencies: [ lowest, highest ]
      fail-fast: false # continue the other jobs if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Common PHP setup
        uses: ./.github/actions/php-setup
        with:
          php: ${{ matrix.php }}
          dependencies: ${{ matrix.dependencies }}

      - name: Run tests on Postgres
        env:
          DATABASE_URL: pgsql://dbtest:dbtest@127.0.0.1:5432/dbtest?serverVersion=18
        run: vendor/bin/phpunit --log-junit build/logs/phpunit/junit.xml

      - name: Upload test results
        uses: ./.github/actions/upload-phpunit-logs
        with:
          php: ${{ matrix.php }}
          database: ${{ matrix.database }}
          dependencies: ${{ matrix.dependencies }}

  phpunit-sqlite:
    name: Test PHP ${{ matrix.php }}, ${{ matrix.database }}, ${{ matrix.dependencies }} deps
    runs-on: ubuntu-latest
    # don't mark the whole pipeline failed if one of those fails, there might
    # be incompatibilities with upcoming PHP versions
    continue-on-error: ${{ matrix.php == '8.6' }}
    strategy:
      matrix:
        php: ['8.4', '8.5', '8.6']
        dependencies: [lowest, highest]
        database: [sqlite]
        include:
          - php: '8.5'
            dependencies: highest
            coverage: true
      fail-fast: false # continue the other jobs if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Common PHP setup
        uses: ./.github/actions/php-setup
        with:
          php: ${{ matrix.php }}
          dependencies: ${{ matrix.dependencies }}
          coverage: ${{ matrix.coverage }}

      - name: Run tests on Sqlite
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db
        run: |
          mkdir -p build/logs/phpunit
          if [ "$COVERAGE" = '1' ]; then
            vendor/bin/phpunit --coverage-clover build/logs/phpunit/clover.xml --log-junit build/logs/phpunit/junit.xml
          else
            vendor/bin/phpunit --log-junit build/logs/phpunit/junit.xml
          fi

      - name: Upload test results
        uses: ./.github/actions/upload-phpunit-logs
        with:
          php: ${{ matrix.php }}
          database: ${{ matrix.database }}
          dependencies: ${{ matrix.dependencies }}

  phpunit-sqlsrv:
    name: Test PHP ${{ matrix.php }}, ${{ matrix.database }}, ${{ matrix.dependencies }} deps
    runs-on: ubuntu-latest
    # don't mark the whole pipeline failed if one of those fails, there might
    # be incompatibilities with upcoming PHP versions
    continue-on-error: ${{ matrix.php == '8.6' }}
    services:
      mssql:
        image: kcollins/mssql:latest@sha256:95c2666d3a7c5dfaaf7247585057285ab7617fdcba213fff70f30ad92ce2a44a
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "StrongP-ssw0rd!"
          MSSQL_DATABASE: dbtest
          MSSQL_USER: dbtest
          MSSQL_PASSWORD: dbtest
        ports:
          - "1433:1433"
    strategy:
      matrix:
        php: [ '8.5', '8.6' ]
        database: [ sqlsrv ]
        dependencies: [ lowest, highest ]
      fail-fast: false # continue the other jobs if one fails
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Common PHP setup
        uses: ./.github/actions/php-setup
        with:
          php: ${{ matrix.php }}
          dependencies: ${{ matrix.dependencies }}

      - name: Run tests on SQL Server
        env:
          DATABASE_URL: sqlsrv://sa:StrongP-ssw0rd!@127.0.0.1:1433/dbtest?serverVersion=16&charset=utf-8&driverOptions[Encrypt]=0
        # not only the (already installed) sqlsrv extension is required, but also the
        # ODBC driver for Linux -> install too
        run: |
          sudo sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" > /etc/apt/sources.list.d/mssql-release.list
          apt-get update
          ACCEPT_EULA=Y apt-get install -y msodbcsql18'
          vendor/bin/phpunit --log-junit build/logs/phpunit/junit.xml

      - name: Upload test results
        uses: ./.github/actions/upload-phpunit-logs
        with:
          php: ${{ matrix.php }}
          database: ${{ matrix.database }}
          dependencies: ${{ matrix.dependencies }}
